# -*- conf -*-
font=DejaVuSansMono:size=12
initial-window-size-chars=90x27
pad=7x5
title=Terminal
locked-title=no

[bell]
visual=yes

[cursor]
#color=2e3a3e dddddd

[colors]
foreground=373737
background=F2F3FC
regular0=000000  # black
regular1=993030  # red
regular2=0C8B72  # green
regular3=eaf34c  # yellow
regular4=5378B6  # blue
regular5=7c77e1  # magenta
regular6=788EB5  # cyan
regular7=bbc3cd  # white
bright0=333333   # bright black
bright1=ff6e67   # bright red
bright2=22514B   # bright green
bright3=f4f99d   # bright yellow
bright4=5b84c8   # bright blue
bright5=9f9ce1   # bright magenta
bright6=69f1eb   # bright cyan
bright7=e6e6e6   # bright white
flash=415e7f
scrollback-indicator=1A1E22 415e7f
alpha=1

[csd]
border-width=2
border-color=ffdddddd

[scrollback]
indicator-position=none
