#!/usr/bin/env dash
pkill wofi

entries=" Main\n Web\n Net\n Doc\n Term\n Media\n Desk"

selected=$(echo $entries|wofi --width 240 --height 300 --dmenu --cache-file /dev/null --prompt="Move Toplevel To Tag.."| awk '{print tolower($2)}')

case $selected in
main)
    hyprctl dispatch movetoworkspace 1;;
web)
    hyprctl dispatch movetoworkspace 2;;
net)
    hyprctl dispatch movetoworkspace 3;;
doc)
    hyprctl dispatch movetoworkspace 4;;
term)
    hyprctl dispatch movetoworkspace 5;;
media)
    hyprctl dispatch movetoworkspace 6;;
desk)
    hyprctl dispatch movetoworkspace 7;;
esac
