# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "thinkpad_acpi" ];
  boot.extraModulePackages = [ ];
  boot.loader.timeout = 3;
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
        "udev.log_level=3"
        "udev.log_priority=3"
        "acpi_backlight=native"
        "fbcon=nodefer"
        "i915.fastboot=1"
        "nowatchdog"
        "quiet"
        "splash"
        "systemd.show_status=false"
        "rd.systemd.show_status=false"
        "loglevel=3"
    ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7a855182-72f3-45e3-8411-72e8f8dd91fa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7a855182-72f3-45e3-8411-72e8f8dd91fa".device = "/dev/disk/by-uuid/7a855182-72f3-45e3-8411-72e8f8dd91fa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C0C7-91F3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableAllFirmware = true;
}
