# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.timeout = 3;
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
        "udev.log_level=3"
        "udev.log_priority=3"
        "acpi_backlight=video"
        "fbcon=nodefer"
        "slab_nomerge"
        "page_alloc.shuffle=1"
        "pti=on"
        "nvme.noacpi=1"
        "nvme_core.default_ps_max_latency_us=0"
        "nowatchdog"
        "quiet"
        "splash"
        "systemd.show_status=false"
        "rd.systemd.show_status=false"
        "loglevel=3"
    ];

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/eebac66d-58fa-4453-b98b-0b9ddfa39599";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/45D9-DAF5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableAllFirmware = true;
}
