#!/usr/bin/env dash
sed -i s/space-dark.conf/bluesky.conf/ /home/void/.config/hypr/hyprland.conf
sed -i s/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/ /home/void/.config/gtk-3.0/settings.ini
sed -i s/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/ /home/void/.config/gtk-4.0/settings.ini
sed -i s/Arc-Darkest/BlueSky-Mountain-Solid/ /home/void/.config/gtk-3.0/settings.ini
sed -i s/Arc-Darkest/BlueSky-Mountain-Solid/ /home/void/.config/gtk-4.0/settings.ini
sed -i s/Flat-Remix-Black-Dark/Adwaita/ /home/void/.config/gtk-3.0/settings.ini
sed -i s/Flat-Remix-Black-Dark/Adwaita/ /home/void/.config/gtk-4.0/settings.ini
sed -i s/Flat-Remix-Black-Dark/Adwaita/ /home/void/.gtkrc-2.0
sed -i s/darkBG/lightBG/ /home/void/.config/waypaper/config.ini
sed -i s/dark/light/ /home/void/.sh/reloadwaybar
sed -i s/dark/light/ /home/void/.sh/reloadwaybar
sed -i s/Arc-Darkest/BlueSky-Mountain-Solid/ /home/void/.gtkrc-2.0
cp /home/void/.local/share/Wallpapers/NixOS-Blue.png /home/void/.local/share/Wallpapers/000-NixOS.png
cp /home/void/.config/foot/light.ini /home/void/.config/foot/foot.ini
cp /home/void/.config/fuzzel/light /home/void/.config/fuzzel/fuzzel.ini
gsettings set org.gnome.desktop.interface icon-theme Adwaita &
gsettings set org.gnome.desktop.interface gtk-theme BlueSky-Mountain-Solid &
gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' &
reloadwaybar &
#SetAsWallpaper /home/void/Pictures/lightBG/1771709560418.png &
SetAsWallpaper /home/void/.local/share/Wallpapers/000-NixOS.png &
#SetAsWallpaper /home/void/Pictures/lightBG/NixOS-Light.png
