#!/usr/bin/env bash

on() {
cat << EOF > /home/void/.sh/grabstatus
#!/usr/bin/env dash
echo 
EOF
hyprctl keyword bindm ,mouse:273,movewindow
}

off() {
cat << EOF > /home/void/.sh/grabstatus
#!/usr/bin/env dash
echo 
EOF
hyprctl keyword unbind ,mouse:273,movewindow
}


case "$@" in
  bindm)
	on;;
  unbind)
	off;;
esac
