#!/usr/bin/env dash
#hyprctl plugin load $(find /nix/store/ -type d -name *hyprbars*)/lib/libhyprbars.so
hyprctl plugin load /home/void/.config/hypr/plugins/libhyprbars.so
hyprctl plugin load /home/void/.config/hypr/plugins/libborders-plus-plus.so
#hyprctl plugin load /home/void/.config/hypr/plugins/libhyprspace.so
#hyprctl plugin load /home/void/.config/hypr/plugins/libhyprexpo.so
