#!/usr/bin/env dash

pkill wofi

entries=" BR\n US\nX"

selected=$(echo $entries|wofi -x 1310 --width 1 --height 120 --dmenu --cache-file /dev/null --prompt="Keyboard Layout"| awk '{print tolower($2)}')

case $selected in
br)
    setlayout br;;
us)
    setlayout us;;
x)
  pkill wofi;;
esac
