#!/usr/bin/env dash
pkill waybar
waybar -c /home/void/.config/hypr/waybar/darkwaybar.conf -s /home/void/.config/hypr/waybar/dark.css 
#waybar -c /home/void/.config/hypr/waybar/darkwaybar2.conf -s /home/void/.config/hypr/waybar/dark.css &
