#!/usr/bin/env dash

pkill wofi

entries=" Fullscreen\n Toggle-Float\n Close\nx"

selected=$(echo $entries|wofi -x 49 -y 792 --width 210 --height 155 --dmenu --cache-file /dev/null | awk '{print tolower($2)}')

case $selected in
fullscreen)
    hyprctl dispatch fullscreen;;
toggle-float)
    hyprctl dispatch togglefloating;;
close)
    hyprctl dispatch killactive;;
   x)
  pkill wofi;;
esac
