#!/usr/bin/env dash
export NO_AT_BRIDGE=1
export QEMU_AUDIO_DRV=alsa
export QEMU_ALSA_DAC_BUFFER_SIZE=512
export QEMU_ALSA_DAC_PERIOD_SIZE=128
cage -d -s -- \
qemu-system-x86_64 \
-m 4G \
-vga virtio \
-enable-kvm \
-cpu host \
-smp 4 \
-audio driver=sdl,model=virtio \
--bios /home/void/Documents/VMs/OVMF_X64.fd \
-cdrom $@


#-bios /usr/share/edk2/x64/OVMF.fd \
