#!/usr/bin/env dash
pkill wofi
entries=" File\n Deadbeef\n Telegram\n Firefox\n Editor\n Calculator\n Gucharmap\n Gtk-Theme\n Blueman\n Wallpapers\n Terminal\n SmartTerminal"

selected=$(echo $entries|wofi -x 0 --width 250 --height 510 --dmenu --cache-file /dev/null --prompt=Applications | awk '{print tolower($2)}')

case $selected in
  file)
    pcmanfm;;
  deadbeef)
    deadbeef;;
  telegram)
    hyprctl dispatch workspace 1; telegram-desktop;;
  firefox)
    firefox;;
  editor)
    Edit;;
  calculator)
    galculator;;
  gucharmap)
    gucharmap;;
  gtk-theme)
    dconf-editor;;
  blueman)
    blueman-manager;;
  wallpapers)
    waypaper;;
  terminal)
    foot;;
  smartterminal)
    foot -a SmartTerm;;
esac
