#!/usr/bin/env dash
pkill wofi
entries=" File\n Deadbeef\n Telegram\n Firefox\n Editor\n Calculator\n Gucharmap\n Gtk-Theme\n Wallpapers\n Terminal"

selected=$(echo $entries|wofi -x 0 --width 240 --height 418 --dmenu --cache-file /dev/null --prompt=Applications | awk '{print tolower($2)}')

case $selected in
  file)
    pcmanfm;;
  deadbeef)
    deadbeef;;
  telegram)
    telegram;;
  firefox)
    firefox;;
  editor)
    foot -a Nano -e nano;;
  calculator)
    galculator;;
  gucharmap)
    gucharmap;;
  gtk-theme)
    dconf-editor;;
  wallpapers)
    wallpaper;;
  terminal)
    foot;;
esac
