#!/usr/bin/env dash

pkill fuzzel 2>/dev/null

entries=" File
 Telegram
 Deadbeef
 Browser
 Editor
 Gimp
 Calculator
 DConf
 Gucharmap
 Gtk-Theme
 Wallpapers
 Terminal
 SmartTerminal"

selected=$(printf '%s\n' "$entries" | fuzzel --dmenu --lines 13 --width 20 --anchor top-left --prompt "Applications > " | awk '{print tolower($2)}')

case "$selected" in
  file)
    pcmanfm
    ;;
  deadbeef)
    deadbeef
    ;;
  telegram)
    kotatogram-desktop
    ;;
  browser)
    firefox
    ;;
  editor)
    lite-xl
    ;;
  gimp)
    gimp
    ;;
  calculator)
    galculator
    ;;
  dconf)
    dconf-editor
    ;;
  gucharmap)
    gucharmap
    ;;
  gtk-theme)
    nwg-look
    ;;
  wallpapers)
    waypaper
    ;;
  terminal)
    foot
    ;;
  smartterminal)
    foot -a SmartTerm
    ;;
esac
