#!/usr/bin/env dash

pkill fuzzel 2>/dev/null

entries=" Light
⏾ Dark"

selected=$(printf '%s\n' "$entries" | fuzzel --lines 2 --dmenu --width 13 --anchor top-right --prompt "Light Switch > " | awk '{print tolower($2)}')

case "$selected" in
  light)
    -bluesky;;
  dark)
    -space-dark;;
esac
