#!/usr/bin/env dash
cd $( dirname "$@")

format="$@"
file="${format#*.}"

if [ "$file" != "7z" -a "$file" != "tar" -a "$file" != "tar.gz" -a "$file" != "gz" -a "$file" != "zip" -a "$file" != "tar.xz" -a "$file" != "tar.bz2" -a "$file" != "rar" ]
then
	echo -n "Choose a format among 7z, tar, tar.xz, tar.bz2, tar.gz, gz or zip: "
	read format

	while [ "$format" != "7z" -a "$format" != "tar" -a "$format" != "tar.gz" -a "$format" != "gz" -a "$format" != "zip" -a "$format" != "tar.xz" -a "$format" != "tar.bz2" ]
	do
		echo "Wrong format"; sleep 1
		echo -n "Choose a format among 7z, tar, tar.xz, tar.bz2, tar.gz, gz or zip: "
		read format
	done

	if [ "$format" == "7z" -o "$format" == "zip" -o "$format" == "rar" ]
	then
		7zr a "$@"."$format" "$@"
	else
		tar -cvzf "$@"."$format" "$@"
	fi

	echo "Archive $@.$format successfully created"; sleep 3


elif [ "$file" == "7z" -o "$file" == "zip" -o "$file" == "rar" ]
then
	7z x "$@"
else
	tar xvf "$@"
fi
