general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 6
    gaps_out = 13
    border_size = 5
    col.active_border = rgb(111114) rgb(040405) rgb(040405) 99deg
    col.inactive_border = rgb(111114)
    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
    resize_on_border = true
    extend_border_grab_area = 1
    hover_icon_on_border = true
}

plugin {
    hyprbars {
        # example config
        bar_height = 22
        bar_title_enabled = true
        bar_text_align = left
        bar_text_font = DejaVu Sans Mono Bold
        bar_text_size = 14
        con_on_hover = true
        bar_color = rgb(16181D)
        bar_part_of_window = true
        bar_precedence_over_border = true
        bar_button_padding = 15
        bar_padding = 12
        col.text = rgb(5378B6)

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(0b0d0f), 18,   , hyprctl dispatch killactive
        hyprbars-button = rgb(0b0d0f), 18,   , hyprctl dispatch fullscreen 1
        #hyprbars-button = rgb(0b0d0f), 18,    , hyprctl dispatch togglefloating
        hyprbars-button = rgb(0b0d0f), 18,   , move_top_level_to
    }

 borders-plus-plus {
        add_borders = 1 # 0 - 9

        # you can add up to 9 borders
        col.border_1 = rgb(262933)
        col.border_2 = rgb(000000)

        # -1 means "default" as in the one defined in general:border_size
        border_size_1 = 1
        border_size_2 = 1

        # makes outer edges match rounding of the parent. Turn on / off to better understan>
        natural_rounding = yes
    }
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    shadow {
    enabled = true
    range = 7
    render_power = 3 
    color = rgb(000000)
    }

    blur {
        enabled = true
        size = 4
        passes = 4
        special = true
        new_optimizations = true
        popups = true
        ignore_opacity = true
 
   }
}

